export const api_data = [
  {
    id: "P001",
    project_name: "Health Tracker App",
    description:
      "A mobile application for tracking health metrics and fitness goals.",
    createdOn: "2024-01-01T10:30:00Z",
    createdBy: "john.doe@example.com",
    modifiedBy: "jane.smith@example.com",
    modifiedOn: "2024-01-15T12:45:00Z",
    status: "Active",
    category: "Healthcare",
    author: "John Doe",
    application_type: "web",
  },
  {
    id: "P002",
    project_name: "E-commerce Platform",
    description: "A scalable e-commerce platform for online retail businesses.",
    createdOn: "2023-11-10T08:15:00Z",
    createdBy: "alice.johnson@example.com",
    modifiedBy: "bob.williams@example.com",
    modifiedOn: "2024-01-20T09:30:00Z",
    status: "In Progress",
    category: "E-commerce",
    author: "Alice Johnson",
    application_type: "web",
  },
  {
    id: "P003",
    project_name: "AI Chatbot",
    description: "A chatbot powered by AI for customer support automation.",
    createdOn: "2024-02-05T14:20:00Z",
    createdBy: "david.miller@example.com",
    modifiedBy: "emma.brown@example.com",
    modifiedOn: "2024-02-10T16:00:00Z",
    status: "Active",
    category: "Artificial Intelligence",
    author: "David Miller",
    application_type: "web",
  },
  {
    id: "P004",
    project_name: "Online Learning Platform",
    description: "A platform for online courses and skill development.",
    createdOn: "2023-09-12T11:45:00Z",
    createdBy: "michael.lee@example.com",
    modifiedBy: "sarah.jones@example.com",
    modifiedOn: "2023-12-01T13:30:00Z",
    status: "Completed",
    category: "Education",
    author: "Michael Lee",
    application_type: "web",
  },
  {
    id: "P005",
    project_name: "Social Media Analytics Tool",
    description: "A tool to analyze social media engagement and trends.",
    createdOn: "2024-01-18T09:10:00Z",
    createdBy: "chris.wilson@example.com",
    modifiedBy: "laura.adams@example.com",
    modifiedOn: "2024-01-25T14:00:00Z",
    status: "In Progress",
    category: "Marketing",
    author: "Chris Wilson",
    application_type: "web",
  },
  {
    id: "P006",
    project_name: "Restaurant Management System",
    description:
      "A software for managing restaurant orders, inventory, and billing.",
    createdOn: "2023-07-25T15:30:00Z",
    createdBy: "oliver.clark@example.com",
    modifiedBy: "emma.davis@example.com",
    modifiedOn: "2023-10-05T10:30:00Z",
    status: "Completed",
    category: "Hospitality",
    author: "Oliver Clark",
    application_type: "web",
  },
  {
    id: "P007",
    project_name: "Real Estate Listings App",
    description: "A mobile app to browse and list real estate properties.",
    createdOn: "2023-12-15T12:00:00Z",
    createdBy: "sophia.martin@example.com",
    modifiedBy: "jason.white@example.com",
    modifiedOn: "2024-01-10T11:20:00Z",
    status: "Active",
    category: "Real Estate",
    author: "Sophia Martin",
    application_type: "web",
  },
  {
    id: "P008",
    project_name: "Inventory Management System",
    description:
      "A cloud-based system for tracking inventory across warehouses.",
    createdOn: "2024-02-01T09:45:00Z",
    createdBy: "william.harris@example.com",
    modifiedBy: "elizabeth.king@example.com",
    modifiedOn: "2024-02-08T14:00:00Z",
    status: "In Progress",
    category: "Logistics",
    author: "William Harris",
    application_type: "web",
  },
  {
    id: "P009",
    project_name: "Freelance Job Portal",
    description:
      "A platform to connect freelancers with clients for various projects.",
    createdOn: "2023-08-22T13:30:00Z",
    createdBy: "emily.hall@example.com",
    modifiedBy: "ryan.baker@example.com",
    modifiedOn: "2023-11-05T16:15:00Z",
    status: "Completed",
    category: "Business",
    author: "Emily Hall",
    application_type: "web",
  },
  {
    id: "P010",
    project_name: "Smart Home Automation",
    description:
      "A system for remotely controlling and automating home devices.",
    createdOn: "2024-03-05T07:00:00Z",
    createdBy: "noah.evans@example.com",
    modifiedBy: "olivia.roberts@example.com",
    modifiedOn: "2024-03-15T09:30:00Z",
    status: "Active",
    category: "IoT",
    author: "Noah Evans",
    application_type: "web",
  },
];
